services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 12345
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 25s

  eureka:
    build: ../eurekaservice
    image: eureka-service-msb
    container_name: eureka
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8761/ > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  gateway:
    build: ../gateway
    container_name: gateway
    image: api-gateway-msb
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_healthy


  stockpriceapp:
    build:
      context: ../stockpriceapp
    image: stock-price-app-msb
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 12345
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    container_name: stockpriceapp
    depends_on:
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy

  stockconsumer:
    build:
      context: ../stockconsumer
    image: stock-consumer-msb
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 12345
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    container_name: stockconsumer
    depends_on:
      rabbitmq:
        condition: service_healthy
      stockpriceapp:
        condition: service_started
      eureka:
        condition: service_healthy


